---
- name: GATEWAY | Enable forwarding sysctl options
  ansible.builtin.lineinfile:
    dest: "/etc/sysctl.conf"
    regexp: "{{ item }}="
    line: "{{ item }}=1"
  with_items:
    - "net.ipv6.conf.all.forwarding"
    - "net.ipv4.ip_forward"
    # - "net.ipv4.ip_nonlocal_bind"
    # - "net.ipv4.tcp_syncookies"
  notify: ["Apply sysctl"]
  when:
    - anro_iptables_gateway_enable | default(false) | bool

- name: GATEWAY | Disable forwarding sysctl options
  ansible.builtin.lineinfile:
    dest: "/etc/sysctl.conf"
    regexp: "{{ item }}="
    line: "{{ item }}=0"
  with_items:
    - "net.ipv4.ip_forward"
    - "net.ipv6.conf.all.forwarding"
    # - "net.ipv4.tcp_syncookies"
    # - "net.ipv4.ip_nonlocal_bind"
  notify: ["Apply sysctl"]
  when:
    - not (anro_iptables_gateway_enable | default(false) | bool)
