---
- name: INSTALL | Remove firewalld to avoid competing firewall managers
  ansible.builtin.apt:
    name: firewalld
    state: absent
    purge: true
  when: anro_iptables_remove_firewalld | bool

- name: INSTALL | Install iptables persistence packages
  ansible.builtin.apt:
    name:
      - iptables
      - iptables-persistent
      - netfilter-persistent
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: INSTALL | Install IP set packages
  ansible.builtin.apt:
    name:
      - ipset
      - ipset-persistent
    state: present
  when: anro_iptables_ipset_enabled | bool
