---
- name: IPSET | Create persistent IPset configuration
  ansible.builtin.template:
    src: etc/iptables/ipsets.j2
    dest: >-
      {{
        anro_iptables_config_dir
        ~ '/'
        ~ anro_iptables_ipset_save_file
      }}
    owner: root
    group: root
    mode: '0644'
  become: true
  notify:
    - Reload ipsets

- name: IPSET | Flush handlers
  ansible.builtin.meta: flush_handlers
