---
- name: Reload ipsets
  ansible.builtin.command:
    argv:
      - "{{ anro_iptables_ipset_command }}"
      - restore
      - -exist
      - -f
      - >-
        {{
          anro_iptables_config_dir
          ~ '/'
          ~ anro_iptables_ipset_save_file
        }}
  register: _anro_iptables_ipset_restore
  changed_when: true

- name: Reload ipv4
  ansible.builtin.command:
    cmd: >-
      {{ anro_iptables_ipv4_command }}
      {{ '--noflush' if anro_iptables_restore_noflush | bool else '' }}
      {{ anro_iptables_config_dir }}/{{ anro_iptables_ipv4_save_file }}
  register: _anro_iptables_ipv4_restore
  changed_when: _anro_iptables_ipv4_restore.rc == 0

- name: Reload ipv6
  ansible.builtin.command:
    cmd: >-
      {{ anro_iptables_ipv6_command }}
      {{ '--noflush' if anro_iptables_restore_noflush | bool else '' }}
      {{ anro_iptables_config_dir }}/{{ anro_iptables_ipv6_save_file }}
  register: _anro_iptables_ipv6_restore
  changed_when: _anro_iptables_ipv6_restore.rc == 0

- name: Restart Docker after firewall change
  ansible.builtin.systemd:
    name: docker
    state: restarted
  when:
    - anro_iptables_docker_enabled | bool
    - anro_iptables_docker_restart_on_change | bool
    - _anro_iptables_docker_running | default(false) | bool

- name: Apply kernel forwarding settings
  ansible.builtin.command:
    cmd: "sysctl -p {{ anro_iptables_sysctl_file }}"
  when: _anro_iptables_forwarding_config.changed
  changed_when: true
