---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: PREPARE | Install test dependencies
      ansible.builtin.apt:
        name:
          - iputils-ping
          - conntrack
        state: present
        update_cache: true
