---
# Docker configuration for molecule testing
ansible_connection: community.docker.docker

container_command: /lib/systemd/systemd # noqa: var-naming[no-role-prefix]
container_privileged: true # noqa: var-naming[no-role-prefix]
container_log_driver: json-file # noqa: var-naming[no-role-prefix]
container_volumes: # noqa: var-naming[no-role-prefix]
  - /sys/fs/cgroup:/sys/fs/cgroup:rw
container_tmpfs: # noqa: var-naming[no-role-prefix]
  - /run
  - /tmp

# Role test variables

anro_iptables_debug: true
# Keep policies permissive for Molecule.
anro_iptables_input_policy: ACCEPT
anro_iptables_forward_policy: ACCEPT
anro_iptables_output_policy: ACCEPT

#
# FILTER
#
anro_iptables_ipv4_filter_rules1:
  - ':MOLECULE_FILTER - [0:0]'
  - '-A INPUT -s 172.30.0.0/24 -p icmp -j MOLECULE_FILTER'
  - '-A MOLECULE_FILTER -j ACCEPT'

#
# NAT
#
anro_iptables_ipv4_nat_rules1:
  - ':MOLECULE_NAT - [0:0]'
  - '-A POSTROUTING -s 172.30.0.0/24 -j MOLECULE_NAT'
  - '-A MOLECULE_NAT -j RETURN'

#
# MANGLE
#
anro_iptables_ipv4_mangle_rules1:
  - ':MOLECULE_MANGLE - [0:0]'
  - '-A OUTPUT -d 172.30.0.0/24 -p icmp -j MOLECULE_MANGLE'
  - '-A MOLECULE_MANGLE -j MARK --set-mark 42'

#
# RAW
#
anro_iptables_ipv4_raw_rules1:
  - ':MOLECULE_RAW - [0:0]'
  - '-A OUTPUT -d 172.30.0.0/24 -p icmp -j MOLECULE_RAW'
  - '-A MOLECULE_RAW -j RETURN'
